services:
  - type: web
    name: backpackhostel-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: backpackhostel
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
